# Generated by Django 5.1.5 on 2025-01-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('registration_number', models.CharField(max_length=15, unique=True)),
                ('seating_capacity', models.IntegerField()),
            ],
        ),
    ]
